/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val objeto = Complejo()
    objeto=Complejo()
    println("Objeto Complejo creado")
    var x:Int=1
    var x:Int=2
}
